alias home="cd $MYHOME"
alias school="cd $SCHOOL"
alias sch="school"
alias dot="cd $DOTFILES"
alias ucsc="ssh ragragg@unix.ucsc.edu"
alias ll="ls -la"
alias cp="cp -i"  # -i makes it so confirm needed for file overwrite
alias mv="mv -i"
# alias grep="grep -n"
alias cvim="nvim -S Session.vim"
alias tvim="nvim -c 'source $DOTFILES/misc/word_mode'" # vim optimized for typing
alias lvim="nvim -c 'source $DOTFILES/misc/latex_mode'" # vim optimized for latex
alias jvim="nvim -c 'source $DOTFILES/misc/nihongo_mode'" # vim optimized for japanese work
alias rgquiz3="python3 $DOTFILES/misc/lvl3test.py"
alias rgquiz2="python3 $DOTFILES/misc/lvl2test.py"
alias rgquiz1="python3 $DOTFILES/misc/lvl1test.py"
alias rgquiz="python3 $DOTFILES/misc/rgquiz/rgquiz.py"
